spring.application.name=api-gateway

server.port=8080

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# Enable Discovery
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true


#User Service
spring.cloud.gateway.routes[0].id=user-service
spring.cloud.gateway.routes[0].uri=lb://USER-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/users/**


#account Service
spring.cloud.gateway.routes[1].id=account-service
spring.cloud.gateway.routes[1].uri=lb://ACCOUNT-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/accounts/**

logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.org.springframework.web=DEBUG